### ISSUE TITLE
Forcer une IP unique pour l'application pour éviter les collisions

### ISSUE THREAD

**Issue by prytoegrian** [libertempo/docker#1]
Les collisions d'IP peuvent être évitées depuis le merge de https://github.com/docker/docker/pull/19001

De cette façon, le vhost peut retrouver ses billes

**Comment by Prytoegrian** [comment]
Pour éviter complètement les collisions, changer aussi les ports peut être pertinent

**Comment by Prytoegrian** [comment]
... Et attendre la dispo de docker 1.10.0 dans les repo
